# This is a dockerfile to test the build on ubuntu 14.04
from	ubuntu:14.04
run apt-get update -qq
run apt-get install -y software-properties-common python-software-properties
run add-apt-repository -y ppa:kubuntu-ppa/backports
run apt-get update
run apt-get install -y libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
run curl -sL https://deb.nodesource.com/setup_12.x | bash -
run apt-get install -y nodejs
WORKDIR /root/node-opencv
add . /root/node-opencv
run	npm install --unsafe-perm --build-from-source || cat npm-debug.log
run make test
